# You can use "%p" to use the player's display name, works both in 'displayName' and 'label'. Formatted with MiniMessage (https://docs.papermc.io/adventure/minimessage/format/)
name: ""
label: ""

nameAlwaysVisible: true

# Can be "swimming", "sleeping", "crouching" or "fall_falling"
pose: "swimming"

# Defines if it can take damage
invulnerable: false

# Can be "default" (Vanilla behavior), "keep" (Keeps the items until the corpse disappears or dies) or "pop" (Pops the items once a player right clicks it)
itemTreatment: "default"
xpTreatment: "default"

gravity: true
immovable: false
health: 5
keepVelocity: true

# In seconds.
lifespan: 300

# The skin to be used. Leave blank to use the player's skin. You can also input a texture or a player's username/uuid.
skin: ""

# Makes the corpses invulnerable to damage that doesn't come from an entity.
onlyAcceptEntityDamage: false